version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    env_file:
      - backend.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - backend.env
    volumes:
      - ./static:/home/bolivia/static
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data: